--DROP SEQUENCE for_id;
DROP TABLE Dommage CASCADE CONSTRAINTS;
DROP TABLE Lieu CASCADE CONSTRAINTS;
DROP TABLE Periode CASCADE CONSTRAINTS;
DROP TABLE Tempete CASCADE CONSTRAINTS;
DROP TABLE Faits CASCADE CONSTRAINTS;
